server {
    listen 80; # IPv4

    server_name localhost; # Use localhost

    location / {
        root /usr/share/nginx/html; # Serve static files
        index index.html index.htm; # Serve index.html
        try_files $uri $uri/ /index.html; # Serve index.html for all other requests
    }

    location /css/ {
        root /usr/share/nginx/html; # Serve static files
        add_header Content-Type text/css; # Set content type
    }

    location /js/ {
        root /usr/share/nginx/html; # Serve static files
        add_header Content-Type application/javascript; # Set content type
    }

    location /img/ {
        root /usr/share/nginx/html; # Serve static files
    }

    location /fonts/ {
        root /usr/share/nginx/html; # Serve static files
        add_header Access-Control-Allow-Origin *; # Allow cross-origin requests
    }
}
