# This is the main Nginx configuration file. It is loaded when the server starts up.
# It is located in /etc/nginx/nginx.conf

events {
    worker_connections 1024; # Default: 1024
}

http {
    include /etc/nginx/mime.types; # This file is included with the default installation
    include /etc/nginx/conf.d/*.conf; # This is where you can include your own configurations
    default_type application/octet-stream; # Default: application/octet-stream
}
