# Manual install properties
server.port=8081
db.url=jdbc:mysql://localhost:3306/defiut
db.username=defiut
db.password=password
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false